"""initial tables

Revision ID: 6d88845ae43f
Revises: 
Create Date: 2026-03-09 02:41:39.459980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d88845ae43f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verticals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collected_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('file_urls', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('platform_metadata', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_trending', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collected_data_collected_at', 'collected_data', ['collected_at'], unique=False)
    op.create_index('ix_collected_data_source', 'collected_data', ['source'], unique=False)
    op.create_index('ix_collected_data_trending', 'collected_data', ['is_trending'], unique=False)
    op.create_index('ix_collected_data_vertical_id', 'collected_data', ['vertical_id'], unique=False)
    op.create_index('ix_collected_data_vertical_source_trending', 'collected_data', ['vertical_id', 'source', 'is_trending'], unique=False)
    op.create_table('vertical_seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vertical_id', sa.Integer(), nullable=False),
    sa.Column('season_window', sa.String(length=50), nullable=False),
    sa.Column('focus', sa.String(length=255), nullable=False),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('example_post', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vertical_seasons')
    op.drop_index('ix_collected_data_vertical_source_trending', table_name='collected_data')
    op.drop_index('ix_collected_data_vertical_id', table_name='collected_data')
    op.drop_index('ix_collected_data_trending', table_name='collected_data')
    op.drop_index('ix_collected_data_source', table_name='collected_data')
    op.drop_index('ix_collected_data_collected_at', table_name='collected_data')
    op.drop_table('collected_data')
    op.drop_table('verticals')
    op.drop_table('contents')
    # ### end Alembic commands ###
