"""add source_id to collected_data

Revision ID: fb9ad3d6cb31
Revises: 6d88845ae43f
Create Date: 2026-03-09 03:16:21.639884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9ad3d6cb31'
down_revision: Union[str, None] = '6d88845ae43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collected_data', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.create_index('ix_collected_data_source_id_unique', 'collected_data', ['source', 'source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collected_data_source_id_unique', table_name='collected_data')
    op.drop_column('collected_data', 'source_id')
    # ### end Alembic commands ###
